[project]
name = "sanity-pack"
version = "0.2.0"
description = "Arknights asset, data extraction, and processing tool"
authors = [
    {name = "Sanity;Gone 0"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "typer (>=0.19.2,<0.20.0)",
    "pydantic (>=2.12.0,<3.0.0)",
    "tenacity (>=9.1.2,<10.0.0)",
    "rich (>=14.2.0,<15.0.0)",
    "rich-progress (>=0.4.0,<0.5.0)",
    "requests (>=2.31.0,<3.0.0)",
    "unitypy (>=1.23.0,<2.0.0)",
    "spine-asset (>=1.1.1,<2.0.0)",
    "pydub (>=0.25.1,<0.26.0)",
    "pycryptodome (>=3.20.0,<4.0.0)",
    "pymongo (>=4.6.0,<5.0.0)",
    "bson (>=0.5.10,<0.6.0)"
]

[tool.poetry]
packages = [{include = "sanity_pack", from = "src"}]

[tool.poetry.scripts]
sanity-pack = "sanity_pack.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
